### ISSUE TITLE
Leatrix Maps for TBC

### ISSUE THREAD

**Issue by GillsITWorld** [leatrix/leatrix-maps-bcc#1]
For Map opacity, when I try and set Moving to 100% and leave my map open while moving, it flickers constantly instead of staying at 100% Opacity.
It works when you leave your mouse over the map (as selectable in the options) even while moving, but the mouse has to be over the map.

**Comment by leatrix** [comment]
Disable all other addons.  Does that fix it?

**Comment by leatrix** [comment]
Closing as this doesn't seem to be an issue with Leatrix Maps.
