### ISSUE TITLE
[Feature Request] Meeting Stone Level Requirements

### ISSUE THREAD

**Issue by boktai1000** [leatrix/leatrix-maps-bcc#10]
Would it be possible to add the Meeting Stone level requirements both to use (level range) and what level range is possible to be summoned? I'm not sure if the two are the same, and would likely require some testing.

Thanks!

**Comment by leatrix** [comment]
Added meeting stone level range (where known) to 2.5.33.alpha.4.  This is the level range required to use the meeting stone.  Also added minimum level required to enter the dungeon (again, if known).  Both require 'Show zone levels' to be enabled.

https://www.curseforge.com/wow/addons/leatrix-maps-bcc/files/all
