### ISSUE TITLE
Alterac Valley map is mistakenly indicated as unexplored

### ISSUE THREAD

**Issue by silverhawke249** [leatrix/leatrix-maps-bcc#12]
when "Show unexplored areas" is checked, Alterac Valley's map is colored as if it's unexplored.
unchecking the option shows Alterac Valley's map normally:
![image](https://user-images.githubusercontent.com/50395934/119646634-f8c1a200-be51-11eb-95c6-8bf82cbc73aa.png)
![image](https://user-images.githubusercontent.com/50395934/119646673-02e3a080-be52-11eb-859e-fc7788f98abc.png)

**Comment by leatrix** [comment]
Update to the latest release (2.5.37).
https://www.curseforge.com/wow/addons/leatrix-maps-bcc

**Comment by silverhawke249** [comment]
i didn't know a new version was out (and already fixed this) when i submitted this!
i was on the previous release, and i can confirm the new release fixed it.
