### ISSUE TITLE
Add Boat to Exodar in Auberdine

### ISSUE THREAD

**Issue by boktai1000** [leatrix/leatrix-maps-bcc#14]
![image](https://user-images.githubusercontent.com/9054563/120019592-42270400-bfae-11eb-8c4c-4c0d7c92e6d4.png)

Currently only has Menethil and Rut'theran/Darnassus

**Comment by leatrix** [comment]
Many thanks for the report.  Added to 2.5.38.alpha.1.
https://www.curseforge.com/wow/addons/leatrix-maps-bcc/files/all
