### ISSUE TITLE
Lua Error going into Hellfire Ramparts / Blood Furnace

### ISSUE THREAD

**Issue by boktai1000** [leatrix/leatrix-maps-bcc#16]
Message: ...lizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:428: attempt to index local 'layers' (a nil value)
Time: Tue Jun  1 17:33:38 2021
Count: 2
Stack: ...lizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:428: attempt to index local 'layers' (a nil value)
[string "@Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua"]:428: in function `CreateZoomLevels'
[string "@Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua"]:415: in function `OnCanvasSizeChanged'
[string "@Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua"]:407: in function `SetMapID'
[string "@Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:35: in function `SetMapID'
[string "@Interface\AddOns\Leatrix_Maps\Leatrix_Maps.lua"]:275: in function <Interface\AddOns\Leatrix_Maps\Leatrix_Maps.lua:271>

Locals: self = <unnamed> {
 0 = <userdata>
 MarkCanvasDirty = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:384
 GetMinZoomViewRect = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:547
 GetNormalizedHorizontalScroll = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:703
 SetPanTarget = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:580
 DenormalizeVerticalSize = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:728
 IsAtMaxZoom = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:647
 AccumulateMouseDeltas = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:248
 ScalingMode = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:293
 GetMap = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:659
 IsZoomingIn = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:639
 ZoomOut = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:601
 ShouldZoomInstantly = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:539
 SetScalingMode = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:289
 targetScale = 1.000000
 GetNormalizedCursorPosition = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:752
 TryPanOrZoomOnClick = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:87
 shouldPanOnClick = false
 SetZoomTarget = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:585
 normalizedPanXLerpAmount = 0.150000
 NormalizeUIPosition = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:747
 OnMouseUp = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:105
 MarkAreaTriggersDirty = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:376
 CalculateViewRect = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:551
 ResetZoom = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:613
 NormalizeHorizontalSize = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:716
 SetNormalizedHorizontalScroll = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:698
 accumulatedMouseDeltaY = 0.000000
 OnLoad = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:7
 Child = <unnamed> {
 }
 zoomLevels = <table> {
 }
 SetShouldPanOnClick = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:527
 accumulatedMouseDeltaX = 0.000000
 scrollYExtentsMin

**Comment by leatrix** [comment]
Disable other addons.  Does it work?

**Comment by boktai1000** [comment]
I'll do some more testing in a bit - in the rush of BC, wasn't sure if it was anything obvious but will follow up when I can - thanks!

**Comment by leatrix** [comment]
Probably caused by another addon conflicting.  I don't get the error when I enter Hellfire dungeons.

**Comment by leatrix** [comment]
Do you see the error every time you enter a dungeon?  If so, next time you enter a dungeon, disable all other addons first and see if that fixes it.  If it does fix it, enable other addons gradually while you leave/enter the dungeon until you find the addon thats causing the errors.  This is how you fix a problem like this.

I don't think it's caused by LTM.  BCC dungeons don't have maps so entering a dungeon shouldn't change anything with the map (so shouldn't cause any errors).  If you are outside of the dungeon and you open the map and zoom right in, then enter the dungeon and open the map, the map will still show the zone outside and it will still be zoomed in because as far as LTM is concerned, you haven't changed maps (since there are no dungeon maps).

However, if you're running another addon which adds dungeon maps, or changes the map when in a dungeon, that may cause an error if LTM is trying to process a map that one of your other addons has changed.  So you need to disable other addons to find out if that's what's happening.

**Comment by boktai1000** [comment]
I finally had a chance to test this again with just Leatrix Maps enabled, and I can reproduce the issue. It seems like any BC Instance I test with, has the Lua error. Here it is again:

Message: ...lizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:428: attempt to index local 'layers' (a nil value)
Time: Tue Jun  8 15:30:51 2021
Count: 1
Stack: ...lizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:428: attempt to index local 'layers' (a nil value)
[string "@Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua"]:428: in function `CreateZoomLevels'
[string "@Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua"]:415: in function `OnCanvasSizeChanged'
[string "@Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua"]:407: in function `SetMapID'
[string "@Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:35: in function `SetMapID'
[string "@Interface\AddOns\Leatrix_Maps\Leatrix_Maps.lua"]:275: in function <Interface\AddOns\Leatrix_Maps\Leatrix_Maps.lua:271>

Locals: self = <unnamed> {
 0 = <userdata>
 MarkCanvasDirty = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:384
 GetMinZoomViewRect = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:547
 GetNormalizedHorizontalScroll = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:703
 SetPanTarget = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:580
 DenormalizeVerticalSize = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:728
 IsAtMaxZoom = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:647
 AccumulateMouseDeltas = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:248
 ScalingMode = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:293
 GetMap = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:659
 IsZoomingIn = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:639
 ZoomOut = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:601
 ShouldZoomInstantly = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:539
 SetScalingMode = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:289
 targetScale = 1.000000
 GetNormalizedCursorPosition = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:752
 TryPanOrZoomOnClick = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:87
 shouldPanOnClick = false
 SetZoomTarget = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:585
 normalizedPanXLerpAmount = 0.150000
 NormalizeUIPosition = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:747
 OnMouseUp = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:105
 MarkAreaTriggersDirty = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:376
 CalculateViewRect = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:551
 ResetZoom = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:613
 NormalizeHorizontalSize = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:716
 SetNormalizedHorizontalScroll = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:698
 OnLoad = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:7
 Child = <unnamed> {
 }
 zoomLevels = <table> {
 }
 SetShouldPanOnClick = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:527
 scrollYExtentsMin = 0.500000
 areaTriggersDirty = false
 scrollXExtentsMin = 0.500000
 S

Pardon the zillion screenshots - trying to prove that this is the only addon that's running (I used Sigma addon manager to save the addons I was using, I have a bunch installed but I only typically have a handful enabled at any given point in time)

![image](https://user-images.githubusercontent.com/9054563/121253423-b4310000-c86e-11eb-9925-dc0dee8263b2.png)

![image](https://user-images.githubusercontent.com/9054563/121253609-f0fcf700-c86e-11eb-8ae2-73001967c7fe.png)

![image](https://user-images.githubusercontent.com/9054563/121253634-f8bc9b80-c86e-11eb-9355-77ad4ac9a7f3.png)

![image](https://user-images.githubusercontent.com/9054563/121253657-0114d680-c86f-11eb-9695-a604511fdd24.png)

![image](https://user-images.githubusercontent.com/9054563/121253692-083be480-c86f-11eb-91dd-78ef92be75ed.png)

![image](https://user-images.githubusercontent.com/9054563/121253720-0f62f280-c86f-11eb-868c-335276c9ec1c.png)

![image](https://user-images.githubusercontent.com/9054563/121253734-15f16a00-c86f-11eb-9765-f10296729abd.png)

![image](https://user-images.githubusercontent.com/9054563/121253761-1db10e80-c86f-11eb-9e84-ec53a342c8f1.png)

![image](https://user-images.githubusercontent.com/9054563/121253785-23a6ef80-c86f-11eb-8864-df6a801b16e2.png)

![image](https://user-images.githubusercontent.com/9054563/121253803-2a356700-c86f-11eb-9be6-42c4c767b77c.png)

![image](https://user-images.githubusercontent.com/9054563/121253828-30c3de80-c86f-11eb-93c5-e11fc4e74e05.png)

![image](https://user-images.githubusercontent.com/9054563/121253854-38838300-c86f-11eb-84ce-51c42d0dff76.png)

![image](https://user-images.githubusercontent.com/9054563/121253875-3e796400-c86f-11eb-99c7-f88e3867dd70.png)

![image](https://user-images.githubusercontent.com/9054563/121253892-43d6ae80-c86f-11eb-9da1-e353bd40b3ce.png)

![image](https://user-images.githubusercontent.com/9054563/121253911-49cc8f80-c86f-11eb-82b1-c9d5be234b9d.png)

**Comment by boktai1000** [comment]
I tried to reproduce it in The Stockades since it's an easy instance for me to test in Azeroth and was unable to reproduce it there - I also didn't notice it in Pre-patch either... else I would have reported it, and I did a lot of leveling/dungeon boosting on a Draenei Shaman. It seems like there's something in particular with Outland / Outland Maps / Outland Dungeons that seems to be causing this.

**Comment by leatrix** [comment]
Thank you for the additional information.  I can reproduce it now.

**Comment by leatrix** [comment]
This bug is caused by 'Auto-change zones' but it stems from the game reporting incorrect information to Leatrix Maps.

When you enter a new zone or sub-zone, 'Auto-change zones' sets the map to your current zone.  For classic dungeons (such as Stockade), there is no dungeon map which means there is no dungeon map ID and therefore the map isn't changed and all is fine.

But for Outland dungeons (tested with Hellfire Ramparts), it's a bit different.  There is still no dungeon map of course but nevertheless the game returns a dungeon map ID - for a dungeon map that doesn't actually exist.  The game should really return nil as it does for classic dungeons but it doesn't.  And because it returns a dungeon map ID, LTM tries to set the map to that ID and that's when you see the error.

So in 2.5.41.alpha.2, LTM will now check to make sure that the game map actually exists and will no longer just rely on the map ID alone.  This should solve the problem.
