### ISSUE TITLE
Questie not showing on latest TBC version of maps

### ISSUE THREAD

**Issue by Valarya** [leatrix/leatrix-maps-bcc#17]
Just installed version 2.5.38  for classic TBC and questie is no longer showing any map information.

Tried uninstalling > reinstalling both Leatrix and Questie to no avail.

**Comment by leatrix** [comment]
It works ok for me.  First off, reload your UI.  If no change, enable only Questie and disable all other addons.  Does it work?  If it does, enable Leatrix Maps to run alongside Questie.  Does it work?

**Comment by Valarya** [comment]
Thanks. I think it just took awhile.  Literally 30 mins after I thought all options exhausted, it all started working. :)
