### ISSUE TITLE
Class Colored Icons do not show up as of today. 

### ISSUE THREAD

**Issue by Foggy-Morning** [leatrix/leatrix-maps-bcc#18]
I had to uncheck that option and use default group icons to see group on the map.

**Comment by ramboozer** [comment]
Has happened to me as well as 5 other people I play with. Happened AFTER wow updated tonight - 6/7/2021

**Comment by staneezy** [comment]
Having this same issue as well

**Comment by Violet-Vibes** [comment]
Having the same issue, I'm using the latest ElvUi update if it has any importance but seems to be broken even when I turn off ElvUi

**Comment by leatrix** [comment]
Thanks for the reports.  Should be fixed in 2.5.39.
Note: You need to restart your game client after installing the update for the icons to show correctly.
