### ISSUE TITLE
Player icons no longer show up on map

### ISSUE THREAD

**Issue by silverhawke249** [leatrix/leatrix-maps-bcc#2]
TBC Beta recently updated and player icons no longer show, though I can still hover over them and see info:

![image](https://user-images.githubusercontent.com/50395934/115407689-d6b97c00-a222-11eb-8346-a73d28f38826.png)

Using latest version (2.5.08) of LTM.

**Comment by leatrix** [comment]
Many thanks for the report and picture.  Should be fixed in 2.5.09.
https://www.curseforge.com/wow/addons/leatrix-maps-bcc/files/all
