### ISSUE TITLE
request - show spirit rez locations on map

### ISSUE THREAD

**Issue by grand-lotus-iroh** [leatrix/leatrix-maps-bcc#22]
i think this is a great idea because leatrix already is practically the perfect map addon. it's just missing this one feature that would be great because than I would feel more safe on the PVP server knowing how much time I have left until I can guesstimate when the enemy faction will run back and spawn to attack me.

maybe you can just edit and add checkbox to "Show points of interest" area when I type `/ltm`?

![image](https://user-images.githubusercontent.com/1291364/121433204-aef4b380-c949-11eb-8112-65e6faa5bdf1.png)

**Comment by leatrix** [comment]
If you have a reliable list of graveyard locations, I'll add them.  There are a few websites listing them but they differ.

**Comment by leatrix** [comment]
Added to 2.5.42.alpha.2.  There's a new setting 'Show spirit healers' (in 'Show points of interest').
https://www.curseforge.com/wow/addons/leatrix-maps-bcc/files/all

**Comment by grand-lotus-iroh** [comment]
Marvelous!
