### ISSUE TITLE
Mail Box Tracking

### ISSUE THREAD

**Issue by FoxRings** [leatrix/leatrix-maps-bcc#25]
The only way i can find to disable map icons for mailboxes, is to disable the addon entirely. This is affecting the full map and mini-map.

**Comment by leatrix** [comment]
Leatrix Maps doesn't show map icons for mailboxes and it doesn't show any icons in the minimap.

**Comment by FoxRings** [comment]
i think another addon is causing a conflict
I am experimenting turning on/off other addons

Turning off every addon but leaving LMaps on causes the issue to disappear.
But turning off Leatrix Maps off (and leaving a few dozen addons active) also causes the icons to also stop tracking.

**Comment by FoxRings** [comment]
I've figured out that Questie is the offending addon
