### ISSUE TITLE
Spirit Healer Symbol changed

### ISSUE THREAD

**Issue by Genetic91** [leatrix/leatrix-maps-bcc#28]
Hi,

since the last update the spirit healers on the world map are shown as ugly green balls, 
instead of the typical grey winged figure.

Is this just a bug or will this be always like that now?

**Comment by leatrix** [comment]
The previous texture (in alpha releases) was difficult to see on the map.  If you have an idea for a better texture, let me know or show me a picture.

**Comment by Talimar** [comment]
How can we turn this off? I don't see it in the options and it's quite useless information for me at least.

**Comment by leatrix** [comment]
If you don't want to see the spirit healer icons, you can disable them in the 'Show points of interest' configuration panel.

**Comment by Talimar** [comment]
Ok thanks. Do I lose anything else by unchecking it?

**Comment by leatrix** [comment]
If you uncheck 'Show spirit healers', spirit healers won't be shown on the map.  That's all.

**Comment by Talimar** [comment]
Ah sorry didn't see the sub-menu. Thanks for the swift replies.
