### ISSUE TITLE
Zone map moves from anchor and becomes unusable.

### ISSUE THREAD

**Issue by sairiss** [leatrix/leatrix-maps-bcc#29]
When i try to left click on the anchor for the zone map, the map moves to the center of my screen and becomes interactable. I can right click on the anchor just fine, but left clicking will always result in the map being stuck in the middle.

**Comment by sairiss** [comment]
![image](https://user-images.githubusercontent.com/86154232/122642230-55be1a00-d0d7-11eb-9a54-5c7a0049acaa.png)
standard

![image](https://user-images.githubusercontent.com/86154232/122642222-4a6aee80-d0d7-11eb-9e72-dccf3d39c4f3.png)
Right click working

![image](https://user-images.githubusercontent.com/86154232/122642240-5eaeeb80-d0d7-11eb-88fb-6a9391894a33.png)
this is what happens when i left click. reset map position is only "fix" (not even a fix, tbh, just makes the map usable)

pls fix because this is causing me to disable leatrix maps entirely.

**Comment by leatrix** [comment]
I know there is a problem with the battleground map at the moment but it's nothing to do with Leatrix Maps.  Disable all addons.  Does that fix it or do you still have problems when left-clicking the battlefield map tab?

**Comment by sairiss** [comment]
disabling all addons had the same issue. it just started showing in the normal spot after disabling all, and then when going to move it the same issue happens. did more searching and it's a blizzard issue, go figure

**Comment by leatrix** [comment]
Yes.  I reported it to Blizzard a few weeks ago along with a couple of other issues with BCC.  Just have to wait for Blizzard to fix it.

**Comment by leatrix** [comment]
In 2.5.43.alpha.x, battlefield map position and opacity are now set from the configuration panel.  just open the panel and drag the map overlay to position it.
https://www.curseforge.com/wow/addons/leatrix-maps-bcc/files/all
