### ISSUE TITLE
[Feature] Dungeon maps

### ISSUE THREAD

**Issue by dlecina** [leatrix/leatrix-maps-bcc#33]
It would be great to have dungeon maps come up when clicking a dungeon entrace, as in retail. [TomCat's Tours](https://www.curseforge.com/wow/addons/tomcats) does this, but the rest of the addon was not quite to my taste, unlike Leatrix Maps.

It would be even better to have an option to choose between the hand-drawn ones from retail and "simply" acting as a shortcut to Atlas (if it is installed).

Thanks!

**Comment by leatrix** [comment]
Suggestions appreciated.
