### ISSUE TITLE
Windows Defender reporting addon as Trojan:Script/Wacatac.B!ml when updating to 2.5.50

### ISSUE THREAD

**Issue by OnceWasPerfect** [leatrix/leatrix-maps-bcc#36]
Windows Defender is now blocking the install of the latest version claiming Trojan:Script/Wacatac.B!ml.  It looks like it doesn't like something when its unzipping the temporary file C:\Users\xxxx\AppData\Local\Temp\CF\yetnChSxpEav0MwHkfp4xw\1.zip.  It also happens with the latest version of Leatrix Plus.  

No other addons that I use need an update at this time to check if its a Curseforge app thing or specific to this addon.  I did try to reinstall a few other addons and defender did not complain. 

I am using a Windows 11 insider build that may be affecting things as well.

**Comment by leatrix** [comment]
https://github.com/leatrix/leatrix-plus-bcc/issues/55

It's reporting fine with the latest definitions.
Try updating your definitions.

**Comment by leatrix** [comment]
Addons have now been updated (where needed). The latest updates should no longer show false positives in Windows Defender.
