### ISSUE TITLE
Request : Auto-centering map on player

### ISSUE THREAD

**Issue by Moonzen** [leatrix/leatrix-maps-bcc#37]
Hi,
I think that would be wonderful to have an option to let the player always centered in the map, even when we are zoomed in.
Would be useful for example to monitor a gathering route while flying, with a map filled with nodes, where we have to zoom in a little.

**Comment by leatrix** [comment]
Added in 2.5.59.alpha.1.  There is a new option 'Center map on player'.  If enabled, the map will stay centered on your location as long as you are not dragging the map or in a dungeon.  No reload required so you can just enable it as required.
