### ISSUE TITLE
An option for smaller party/raid icons on the map.

### ISSUE THREAD

**Issue by Nillx** [leatrix/leatrix-maps-bcc#4]
I would love an option that makes the party/raid dots on the map smaller, similar to Retail's size on the map. Currently in Classic sometimes its a bit difficult to see the battleground objective when there are a few people around it. Example here, i had to zoom in to see the graveyard name and it was almost completely covered. 
![wddwa](https://user-images.githubusercontent.com/34476875/118365889-30556200-b5a7-11eb-820e-053518545d2b.JPG)

**Comment by leatrix** [comment]
Thanks for the feedback.  Release notes for Leatrix Maps 2.5.10 for Burning Crusade Classic:
- Enlarge player arrow - default icon size is now 28 (was 27) and the range is now 50% to 200%.
- Class colored icons - range is now 50% to 200%.
- Enhance battlefield map - default icon size is now 16 (was 20) and the range is now 50% to 200%.

**Comment by Nillx** [comment]
Thanks!

**Comment by Nillx** [comment]
Also talking about smaller stuff, what about letting us also scale down the size of Fly path icons and Portal icons? They look somewhat huge compared to the rest of the map when you scale down the map size.
![dwdwa](https://user-images.githubusercontent.com/34476875/118412580-78f24580-b6a3-11eb-95a1-9a1a53456d30.JPG)
