### ISSUE TITLE
Cannot see players in party or raid on big map after latest update to  leatrix maps.

### ISSUE THREAD

**Issue by wazerstar** [leatrix/leatrix-maps-bcc#40]
A quick video showing it.

I got it confirmed by many others players using leatrix that it is now broken.

Reverting back to older version works.

Video.
https://streamable.com/w8zr5l

Another issue is that the version shows different version installed than compared on curse where its downloaded from

https://i.imgur.com/pd42a9b.png

**Comment by leatrix** [comment]
All Leatrix addons now use a third party packager to fix the CurseForge App issue. The addon version, game version, change log, etc, are now showing correctly in the app. If the latest updates don't show up in CurseForge App, close the app and launch it again.

**Comment by wazerstar** [comment]
@leatrix thanks now works! :)
