### ISSUE TITLE
Feature Request - Max Zoom In

### ISSUE THREAD

**Issue by Rumchiller** [leatrix/leatrix-maps-bcc#41]
I am using a 4k screen and this addon as a second minimap. Is it possible to zoom in further? For me it looks like WoW is handling the max zoom in level?

**Comment by leatrix** [comment]
Try 2.5.64.alpha.x.  There is a new option 'Increase zoom level' which doubles the maximum zoom level for the world map (so you can zoom in twice as much).  If there are no issues with it, I can add a configuration panel for it.

https://www.curseforge.com/wow/addons/leatrix-maps-bcc/files/all

**Comment by Rumchiller** [comment]
Hey, thanks for that incredible fast response. I've tested it, for now it works like a charme.

**Comment by leatrix** [comment]
With the latest alpha, you can set your own maximum zoom level (up to 600%) for both the world map and the battlefield map frame.
