### ISSUE TITLE
BattlefieldTabFrame active when zone map is disabled

### ISSUE THREAD

**Issue by bloodstrike** [leatrix/leatrix-maps-bcc#43]
Using Leatrix Maps BCC 2.5.67 with all other addons disabled, if I hover over where the Zone Map **Tab** _should_ be, I can see the tooltip for the zone map tab even though the zone map is disabled. (Screenshot doesn't capture cursor, but my cursor is currently hovering over nothing visible to the right of the ltm options panel).

![Screen Shot 2021-11-15 at 10 28 42 AM](https://user-images.githubusercontent.com/1264614/141808817-6e2652ab-e206-470a-8d79-d8bb836d8f3d.png)

I can even right click on it and get the context menu for the zone map tab:

![Screen Shot 2021-11-15 at 10 38 13 AM](https://user-images.githubusercontent.com/1264614/141810143-e59c72bc-848c-45c5-babd-05ff0cd913cf.png)

If I change 'Zone Map' to 'Always' and then back to 'Never' this issue goes away until I log off or reload the interface, then it reoccurs. Disabling ltm also eliminates the problem. Also tried deleting all savedvaraibles related to ltm, but the issue still happens.

Poking around, the frame that is creating the tooltip is the 'BattlefieldMapTab' frame which appears to be separate from the BattlefieldMapFrame.

**Comment by leatrix** [comment]
Many thanks for the excellent bug report.  Tested with all addons disabled, lots of information and screenshots included - outstanding.

This is indeed a minor bug and should be fixed in 2.5.68.alpha.1.
https://www.curseforge.com/wow/addons/leatrix-maps-bcc/files/all

**Comment by bloodstrike** [comment]
Glad to help! Thanks!

**Comment by bloodstrike** [comment]
Installed 68.alpha.1 - issue seems to be resolved if 'Enhance battlefield map' is checked, but if it is unchecked the same issue happens.

**Comment by leatrix** [comment]
Should be fixed in alpha.2.  I moved the fix to the main block of code (rather than just the Enhance battlefield map block).
