### ISSUE TITLE
World Map Not Opening After Update

### ISSUE THREAD

**Issue by eminorgh** [leatrix/leatrix-maps-bcc#45]
Just as the title says.  After the Leatrix Plus & Leatrix Maps updates from the past couple days, the world map no longer will open.  I have to disable the addon to see the world map.  Tried reinstalling, deleting cache, reverting to previous versions, nothing will work.  Leaving Leatrix Plus active with Leatrix Maps disabled is the only way I can get the world map to open.

**Comment by leatrix** [comment]
Disable all other addons.  Try again.  Report back when you have done that.  Someone else reported an issue with Move And Improve.  Are you using that?

**Comment by eminorgh** [comment]
Yes! I am, I'll try that right now and report back.

**Comment by eminorgh** [comment]
Sure enough, that did the trick!  Thank you so much for the super fast response! I'll leave Move & Improve disabled, I'd MUCH rather have Leatrix functioning haha.  In case anyone has trouble finding the file (like I did), it's listed as "D4KiR MoveAndImprove"

**Comment by leatrix** [comment]
If you want to use MAI, install the latest LTM alpha (currently 2.5.71.alpha.3).  It fixes the conflict with MAI as long as you don't enable 'Sticky map frame'.

https://www.curseforge.com/wow/addons/leatrix-maps-bcc/files/all

> 2.5.71.alpha.3 - 3rd December 2021
> - Improved compatibility with Move And Improve addon.  If you are using MAI, don't use 'Sticky map frame' in LTM.

**Comment by leatrix** [comment]
2.5.71.alpha.4 - 3rd December 2021
- If you have Move And Improve addon installed, the world map will now open but Leatrix Maps won't be able to position it and the 'Sticky map frame' setting won't do anything.

**Comment by SoterDarkknight** [comment]
I have this issue. All other addons are disabled ingame and reloaded. I just sounds the maps i opening, but nothing is happening.

**Comment by leatrix** [comment]
@SoterDarkknight Try 2.5.71.alpha.6.
https://www.curseforge.com/wow/addons/leatrix-maps-bcc/files/all

If that doesn't work, open the panel with /ltm and click the 'Reset Map Layout' button in the bottom-right corner.

If that doesn't work, enter '/ltm wipe'.

**Comment by SoterDarkknight** [comment]
thanks :-) /ltm and click the 'Reset Map Layout'  did the trick

**Comment by leatrix** [comment]
Looks like the new MAI update (2021.12.04-18:45) fixed the problem with the map so the MAI fix has been removed from LTM 2.5.71.alpha.7 (as well as the latest Classic Era alpha).
