### ISSUE TITLE
[Enhancement] Zone crossings - Exodar

### ISSUE THREAD

**Issue by Road-block** [leatrix/leatrix-maps-bcc#46]
Exodar is missing a zone crossing POI for the side entrance to the city. 
Same for the connecting point at the Exodar city map.

![image](https://user-images.githubusercontent.com/109839/145220758-32e7e55e-086c-45ee-a5ba-09f31514d843.png)

**Comment by leatrix** [comment]
Many thanks.  Added The Vault of Lights zone crossings to Exodar and Azuremyst Isle maps in 2.5.74.alpha.1.
