### ISSUE TITLE
Enhance dressup option makes char stats disappear

### ISSUE THREAD

**Issue by Oliaxz** [leatrix/leatrix-maps-bcc#48]
When i enable the enhance dressup option it makes the char stats disappear in character panel. Seems to be a recent issue.

**Comment by leatrix** [comment]
Read the setting tooltip.

> You will be able to middle-click the character model in the character frame to toggle character attributes.

It's actually awesome because you can have a retail style character model that you can zoom and rotate but still have all the stats you need whenever you want them with a middle-click.  It's not a recent change.  It's been like this since 2.5.32 (17th May 2021).
