### ISSUE TITLE
Set Map Opacity not keeping non-default setting

### ISSUE THREAD

**Issue by foxythefoxer** [leatrix/leatrix-maps-bcc#49]
Any of the "Set Map Opacity" setting does not keep any changes. If I change any of the settings (stationary %, Moving %, Unchecking pointing at map. Even unchecking The entire setting of Set Map Opacity) none of those settings are saved. and they just use the default addon options, Which are Stationary 100%, Moving 50%, and Use stationary opacity while pointing at map. 

The setting do stick for a single opening of the map. But once you close the map and open the map a second time they revert back to default options no matter what. 

![map should be 100, but is 50 percent](https://user-images.githubusercontent.com/75973531/149646915-df9ca483-6a34-48b8-a672-f01b0a9d44b9.png)

**Comment by foxythefoxer** [comment]
After reading through other issues, I found this to be caused by another addon.

**Comment by leatrix** [comment]
Unfortunately, TomCatTours doesn't have a configuration panel at all for BCC/Classic so there's no way to disable settings that you don't need or that might conflict with other addons.

If you just want to disable map fade completely with TomCatTours, enter this into chat:

/run SetCVar("mapFade", 0)

TomCatTours should no longer fade the map when your character is moving and that should survive reloads too.  The opacity settings in LTM might not work as they should (while TomCatTours is enabled) but the map shouldn't fade.
