### ISSUE TITLE
Missing green arrow to Silvermoon

### ISSUE THREAD

**Issue by Iowerth** [leatrix/leatrix-maps-bcc#51]
There is no green arrow to Silvermoon. And because of this it is impossible to get to Silvermoon from map.
Version 2.5.88.
![2022-02-01 19_31_14-Window](https://user-images.githubusercontent.com/10152411/152010205-3f844d10-1747-45a7-98c6-ac1ca309cc64.jpg)

**Comment by leatrix** [comment]
Many thanks.  Added to latest alpha.

> 2.5.89.alpha.1 - 1st February 2022
> - Added zone crossings for Eversong Woods and Silvermoon City.
> - Added Orb of Translocation for Silvermoon City and Undercity.
