### ISSUE TITLE
small map and every thing else is big 

### ISSUE THREAD

**Issue by xRuzel** [leatrix/leatrix-maps-bcc#8]
I got an issue where is my map is very small and everything else in it is big for example the player arrow and the dungeon location and party player tried to disable all the addons and left leatrix map on but that didn't help and the issue still the same.

if I enlarge the map it gets worse. Hope there is a fix for this.
![WoWScrnShot_052121_232149](https://user-images.githubusercontent.com/84594111/119188229-702ab680-ba8b-11eb-846e-091cafa222b7.jpg)
![WoWScrnShot_052121_231727](https://user-images.githubusercontent.com/84594111/119188238-7325a700-ba8b-11eb-8e44-e6c9f17a34c5.jpg)

**Comment by leatrix** [comment]
For LTM, you can change the size of the player arrow ('Enlarge player arrow') and player icons ('Class colored icons') in the addon settings.  Click the little configuration buttons next to the options.

Your screenshots shows that you have another addon installed which is showing dungeon icons so they are nothing to do with LTM.

Can you attach a screenshot showing the same maps but only LTM installed?

**Comment by xRuzel** [comment]
I re-installed leatrix and here you can see the addon without any other addon on I think this is fixed after the re-installation will try to turn on the addons 1 by 1 and see if the issue will come back again.

and ty for the how to fix the player arrow 
![WoWScrnShot_052121_234231](https://user-images.githubusercontent.com/84594111/119190337-445d0000-ba8e-11eb-988f-8ebaefd4d341.jpg)

**Comment by ReGdYN** [comment]
I've had the exact same issue.
The problem was "TomCat's AddOn Suite (formerly TomCat's Tours)".
Back to normal now.

**Comment by leatrix** [comment]
Thanks for your input, ReGdYN.  The problem does indeed appear to be TomCat's Addon Suite.
This issue is related:
https://github.com/leatrix/leatrix-maps-bcc/issues/19
